services:
  - type: web
    name: goodcat-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: VAPID_PUBLIC
        sync: false
      - key: VAPID_PRIVATE
        sync: false
